pool:
  vmImage: ubuntu-latest
stages:
- stage: cd
  displayName: Continuous deployment
  jobs:
  - job: docker_build
    displayName: Build Docker Container image
    steps:
    - task: Docker@2
      displayName: Build Docker container image
      inputs:
        containerRegistry: 'azure_acr'
        repository: 'dotnetwebapp'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest